language: go
go:
    - 1.4
    - tip
sudo: false
before_install:
    - sudo apt-get update
    - sudo apt-get install libgl1-mesa-dev xorg-dev
    - go get -u github.com/go-gl/glfw/v3.1/glfw
notifications:
    email:
        recipients:
            - joshua.wales@gmail.com
        on_failure: always
