language: go
go:
    - 1.4
    - tip
before_install:
    - sudo apt-get update
    - sudo apt-get install libtool
notifications:
    email:
        recipients:
            - joshua.wales@gmail.com
        on_failure: always
